# TODO checkout https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

# TODO change these
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dirt # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

comments:
  # provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman_v2", "staticman" "custom"
  provider: disqus
  disqus:
    shortname: weilu-community
  # discourse:
  #   server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  # facebook:
  #   # https://developers.facebook.com/docs/plugins/comments
  #   appid                :
  #   num_posts            : # 5 (default)
  #   colorscheme          : # "light" (default), "dark"

paginate: 20 # amount of posts to show
paginate_path: /page:num/

include: ["_pages"]

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      # read_time: true
      comments: true
      # share: true
      # related: true
  # _pages
  -
    scope:
      path: ''
      type: pages
    values:
      layout: single
      # author_profile: true
