# TODO checkout https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

# TODO change these
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

comments:
  # provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman_v2", "staticman" "custom"
  provider: disqus
  disqus:
    shortname: weilu-community
  # discourse:
  #   server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  # facebook:
  #   # https://developers.facebook.com/docs/plugins/comments
  #   appid                :
  #   num_posts            : # 5 (default)
  #   colorscheme          : # "light" (default), "dark"

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: single
      comments: true
  # -
  #   scope:
  #     path: ''
  #     type: "pages"
  #   values:
  #     layout: 
